services:
  - type: web
    name: fluxocaixa
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.fluxocaixa.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHONPATH
        value: src
      - key: DATABASE_URL
        value: sqlite:///./instance/fluxo.db
      - key: PYTHON_VERSION # Opcional: Especifique a versão do Python se necessário
        value: "3.10" # Exemplo, ajuste para a versão que você usa (ex: 3.8, 3.9, 3.10, 3.11, 3.12)

